### ISSUE TITLE
Ignore images in code snippets

### ISSUE THREAD

**Issue by kendallgassner** [github/accessibility-alt-text-bot#30]
If a user adds an image in a code snippet, we should ignore the alt text.

```
<img alt='' src='' /> 
```

**Comment by khiga8** [comment]
This ties to https://github.com/github/accessibility-alt-text-bot/issues/28, which I believe is raising a false positive due to the code snippet in the release notes.

I think the long term solution is going to be to use a markdown parser like markdownlint to parse the markdown body and raise errors, rather than regex matching the string with bash like we currently do. This would be a pretty big overhaul of the code, but we do have existing markdownlint rules we could use in [markdownlint-github](https://github.com/github/markdownlint-github).
